fix: ensure descending order in x data
cheminfo/convert-to-jcamp pull request #65
Opened 2023-04-05 07:14 UTC by jobo322

reduce size of jcamp using the spectral width and the number of points it is similar to the exported jcamp from bruker topspin

2023-04-06 04:37 UTC, lpatiny requested changes

2023-04-06 04:37 UTC, lpatiny commented on src/from1DNMRVariables.ts
>  function isPeakData(
It should not be called PeakData but XYData (please change everywhere). PeakData is used for mass spectrometry fragmentation but for NMR we have equidistant x values.

2023-04-06 04:37 UTC, lpatiny commented on src/from1DNMRVariables.ts
>      (e) =>
Please rename `e` to `key`

2023-04-06 04:37 UTC, lpatiny commented on src/from1DNMRVariables.ts
> +  const newVariables = JSON.parse(
This is extremely slow and should not be used. We need to make a zoom to discuss about this PR.

2023-04-09 06:46 UTC, targos commented
No tests?

2023-04-10 12:56 UTC, merged